name:                hsbuster
version:             0.1.0.0
github:              "m074/hsbuster"
license:             BSD3
author:              "mota"
maintainer:          "example@example.com"
copyright:           "2020 mota"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- DeriveDataTypeable
- ScopedTypeVariables
- OverloadedStrings

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hsbuster#readme>

dependencies:
- base >= 4.7 && < 5
- network
- cmdargs
- stm
- bytestring
- network-simple
- split


library:
  source-dirs: src


executables:
  hsbuster-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-cse
    dependencies:
    - hsbuster


tests:
  hsbuster-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsbuster
 